### ISSUE TITLE
Remove android auto print margin

### ISSUE THREAD

**Issue by naorz** [katzer/cordova-plugin-printer#81]
Hi,
I'm trying to print a DOM element, but there is an unwanted margin around the paper.
How can I remove it or take control of it?
* Margin example:

* Content that I sent for test (replaces  "[PRINT_CONTENT]"):

```html
<div>test</div>
```

1. [Remove unwanted white space in webview android](http://stackoverflow.com/questions/8694184/remove-unwanted-white-space-in-webview-android)

2. Second try, via CSS, so I insert style as a prefix (or build a full html, just for the test)
2.a. As a prefix:

```css
html, body {
      position: relative;
      width: 100%;
      height: 100%;
      margin: 0 !important;
      padding: 0 !important;
      border: black solid 1px;
    }
    * {
      margin: 0 !important;
      padding: 0 !important;
    }
```

2.b. as a full html (replace "[PRINT_CONTENT]" with my content)
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
  <title>test</title>
  <style>
    html, body {
      position: relative;
      width: 100%;
      height: 100%;
      margin: 0 !important;
      padding: 0 !important;
      border: black solid 1px;
    }
    * {
      margin: 0 !important;
      padding: 0 !important;
    }
  </style>
</head>
<body>
[PRINT_CONTENT]
</body>
</html>
```
